### ISSUE TITLE
Implement component for mounting and unmounting single-spa parcels.

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-vue#14]
See https://single-spa.js.org/docs/ecosystem-react.html#parcels for how single-spa-react is doing this.

**Comment by hui-fly** [comment]
Does this project support hash mode?
I used the hash mode but it didn't take effect and the route did not jump normally

**Comment by joeldenning** [comment]
@hui-fly your comment is a duplicate of https://github.com/single-spa/single-spa-vue/issues/44 and belongs in that issue. This issue is for single-spa parcels.

**Comment by joeldenning** [comment]
Here's how single-spa-react does it: https://github.com/single-spa/single-spa-react/blob/master/src/parcel.js

**Comment by MarcoBomfim** [comment]
I'll see if I come up with something for this.

**Comment by filoxo** [comment]
This is released in [single-spa-vue@2.1.0](https://github.com/single-spa/single-spa-vue/releases/tag/v2.1.0) and documented at [single-spa-vue "Rendering a parcel"](https://single-spa.js.org/docs/ecosystem-vue/#rendering-a-parcel).
