### ISSUE TITLE
1.8.0

### ISSUE THREAD

**Issue by jyear** [single-spa/single-spa-vue#35]
When I upgraded from 1.7.0 to 1.8.0, I found that the render mode of Vue was changed from replace el to append under El

**Comment by joeldenning** [comment]
That is the intentional behavior we changed in 1.8.0. See https://github.com/single-spa/single-spa-vue/releases/tag/v1.8.0 and #33.

In single-spa@<=1.7.0, this behavior only applied when you omitted appOptions.el, but now it applies also when you do not omit appOptions.el

**Comment by joeldenning** [comment]
Thinking more about this - maybe would have been better to publish as 2.0.0 to avoid confusion / breaking things. Next time I'll be more conscious of this.
