### ISSUE TITLE
If there are multiple instances of one component, unmount does not work properly

### ISSUE THREAD

**Issue by madeofsun** [single-spa/single-spa-vue#37]
If I have several instances of same single-spa-vue component, there is an error on unmount, resulting in memory leak.

Console reports: "Cannot read property '$destroy' of undefined" in that function.

```javascript
function unmount(opts, mountedInstances) {
    return Promise.resolve().then(() => {
      mountedInstances.instance.$destroy();
      mountedInstances.instance.$el.innerHTML = "";
      delete mountedInstances.instance;

      if (mountedInstances.domEl) {
        mountedInstances.domEl.innerHTML = "";
        delete mountedInstances.domEl;
      }
    });
  }
```
Further investigation shown that the problem is how instances are stored.

`mountedInstances` is created only one time, when single-spa hooks are created.

``` javascript
export default function singleSpaVue(userOpts) {
  // ...
  let mountedInstances = {};

  return {
    bootstrap: bootstrap.bind(null, opts, mountedInstances),
    mount: mount.bind(null, opts, mountedInstances),
    unmount: unmount.bind(null, opts, mountedInstances),
    update: update.bind(null, opts, mountedInstances)
  };
}
```

And in the mount method `mountedInstances.instance` get overwritten every time mount is called, so `mountedInstances.instance` keeps only recent value.

```javascript
function mount(opts, mountedInstances, props) {
  return Promise.resolve().then(() => {
    // ...

    mountedInstances.instance = new opts.Vue(appOptions);
    if (mountedInstances.instance.bind) {
      mountedInstances.instance = mountedInstances.instance.bind(
        mountedInstances.instance
      );
    }
    return mountedInstances.instance;
  });
}
```

This causes the error, because every time unmount is called, same `mountedInstances.instance` is used for all of them, which is deleted on the very first call.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-vue/releases/tag/v1.8.1 - thanks for your contribution
