### ISSUE TITLE
Issues mounting multiple Vue parcels on other Vue App

### ISSUE THREAD

**Issue by Muddasir-Shakil** [single-spa/single-spa-vue#40]
Hi,
I am creating a distributed application for machine visualization, and I am testing micro frontend architecture to do so. I have created another HMI app where I am integrating the distributed components. So for this I am using parcels from distributed components to integrate them into HMI app. So far the parcels are mounted and can be seen on the HMI app. I have three Distributed (Vue) apps running which needs to be integrated into HMI (Vue) app. The problem is out of three only 1 app is responding and other apps seems to be mounted but inactive. I noticed the pattern that always the app that that is mounted the last is always responsive and rest do nothing when even I click on them. The template and mounting code is as follows for the Parcel page. 
```javascript
<template>
  <div id="app">
    <div class="supply">
      <div id="conveyor-app"></div>
    </div>
    <div id="sorting-app" class="sorting"></div>
    <div id="picking-app" class="picking"></div>
  </div>
</template>

 loadParcel() {
      /*global System*/
      const elNames = ["conveyor-app", "sorting-app", "picking-app"];
      var domElements;
      elNames.forEach(element => {
        var domElement = document.getElementById(element);
        //  mountParcel(() => System.import(element), { domElement });
        mountRootParcel(() => System.import(element), {
          domElement
        });
      });
    }

**Comment by joeldenning** [comment]
Which version of single-spa-vue are you using? We recently fixed a bug in https://github.com/single-spa/single-spa-vue/pull/38 that was released in 1.8.1 that might be related.

**Comment by Muddasir-Shakil** [comment]
I am using 1.5.2

**Comment by Muddasir-Shakil** [comment]
After updating all my vue app to single-spa-vue 1.8.1, it did not work. The parcels are mounted but do not response to anything. Like clicking or anything

**Comment by joeldenning** [comment]
That's a problem I haven't seen before. Could you provide a code sandbox or github repo that demonstrates the problem?

**Comment by Muddasir-Shakil** [comment]
This issue is solved. Updating the single-spa-vue to 1.8.1 solved the issue. you can close now. Thank you for your help
