### ISSUE TITLE
automatically integrate with vue devtools

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-vue#45]
See https://single-spa.slack.com/archives/CGGUQJMK6/p1586184682018500?thread_ts=1586160528.018200&cid=CGGUQJMK6

In vue-cli-plugin-single-spa, we should do this:

```
// Before you create app
Vue.config.devtools = process.env.NODE_ENV === 'development'
```

In single-spa-vue, we should automatically initialize the devtools with the following:

```
window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = instance.constructor
```

**Comment by joeldenning** [comment]
Closing this, as explained in #46

**Comment by bwcgn** [comment]
When you are planning a release of this?

**Comment by frehner** [comment]
nothing to release. see https://github.com/single-spa/single-spa-vue/pull/46#issuecomment-610481046

**Comment by joeldenning** [comment]
This issue was closed without making any changes to single-spa-vue. Vue devtools 5.3.3 fixed this issue and we no longer have to make any changes to single-spa-vue for it.

There are no unreleased changes in single-spa-vue -- our latest code was released in 1.8.2

**Comment by joeldenning** [comment]
Oops, I commented right after @frehner did. I didn't mean to double-team this one 😄

**Comment by bwcgn** [comment]
awesome, cheers.
