### ISSUE TITLE
How i can use custom props data in Vue application Component

### ISSUE THREAD

**Issue by pravinshinde** [single-spa/single-spa-vue#50]
```
@joeldenning, 
    "single-spa": "^5.5.3",
    "single-spa-vue": "^1.8.2",

I have shared common **service instance** created with the help of '**rxjs**' to achieve ** inter app communication** between two application as: 
singleSpa.registerApplication({
                      name: 'app1',
                      app: () => window.System.import('app1'),
                      activeWhen: location => location.pathname.startsWith('/app1'),
                      customProps: (name, location) => {
                        return { messageService: messageService };
                      }
                 });

I'm retrieving those **custom props** in child app **app1** as:
           export const mount = props => vueLifecycles.mount(props).then(instance => {
                  // do what you want with the Vue instance
                 console.log('Data', props)
                 console.log('Vue instance', instance)
          });

Here, I'm able to get props data & vue instance with props data as :
```
![interApp_communication](https://user-images.githubusercontent.com/8956879/87846304-91130000-c8ec-11ea-873c-78ef9a4700e9.png)

```
I have created vue instance like: 
                   const vueLifecycles = singleSpaVue({
                            Vue,
                            appOptions: {
                                render: (h) => h(App),
                                router,
                                store,
                           },
                 });

How should i get that message-service instance in my component from Vue instance? So that i can use that & implement Inter App communication.
```

**Comment by joeldenning** [comment]
Good question - I just pushed some commits to the vue-microfrontends example that shows how.

https://github.com/vue-microfrontends/root-config/blob/a43d19d3171b56aecba9d94a362d3cd5fdae8065/src/vue-mf-root-config.js#L7-L9

https://github.com/vue-microfrontends/navbar/blob/c99da565d1898b9b8b477dbc786836fc699e2cd3/src/main.js#L14

https://github.com/vue-microfrontends/navbar/blob/c99da565d1898b9b8b477dbc786836fc699e2cd3/src/App.vue#L59-L61

https://github.com/vue-microfrontends/navbar/blob/c99da565d1898b9b8b477dbc786836fc699e2cd3/src/App.vue#L46

I also plan on updating vue-cli-plugin-single-spa to document this in the main.js file. Also I plan on pull requesting the single-spa docs with this information.

**Comment by joeldenning** [comment]
I added documentation for this in https://github.com/single-spa/single-spa.js.org/pull/301

**Comment by joeldenning** [comment]
I've updated vue-cli-plugin-single-spa to make this more obvious in https://github.com/single-spa/vue-cli-plugin-single-spa/pull/11
