### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by tdowdle** [single-spa/single-spa-vue#51]
Hello,

Is there a way to get this working within Vue 3?

Vue 3 no longer exports vue e.g. `import Vue from 'vue';` doesn't exist.

Is there a work around?

Thanks

**Comment by joeldenning** [comment]
I haven't tried single-spa-vue with Vue 3 yet. I might be able to look into this in the next couple days. If others have interest in helping out with this, that would also be appreciated.

**Comment by filoxo** [comment]
Related information: https://github.com/single-spa/create-single-spa/issues/168#issuecomment-673508871

**Comment by joeldenning** [comment]
This repo shows Vue 3 working with single-spa. It has a modified single-spa-vue file.

https://github.com/joeldenning/vue-3-single-spa

**Comment by joeldenning** [comment]
Documentation for it (still pending a new single-spa-vue release) - https://github.com/single-spa/single-spa.js.org/pull/313
