### ISSUE TITLE
Problem with Vuetify select component 

### ISSUE THREAD

**Issue by Zdanc32** [single-spa/single-spa-vue#54]
When I use select component I cannot close actives selectors. I don't know where I make mistake. Before the app was working correctly, but when I add vue single-spa I have this problem. 

![obraz](https://user-images.githubusercontent.com/12541691/91829137-561d1f80-ec41-11ea-99e2-7bbbdff3c057.png)

Sorry for polish language at screen :)

**Comment by joeldenning** [comment]
Hi @Zdanc32, could you provide a demonstration of the issue. A Code Sandbox or Github repo that shows the problem would be helfpul here in diagnosing the issue.

**Comment by Zdanc32** [comment]
Sorry, I have invalid micro-frontend service. The one guy from my team, overwrite INPUT in one service and that case overwirte all INPUT-s in all services... Sorry guys. This is our first up where we use single-spa and micro-fronted serivces. Protip, if you want to make sure about the service correctly work you have to make sure you have one .css style guid.

I wrote this issue, because I losed any hope... And today I start working that example repository with these problems and I created new root-config, and new single-spa app... And everything work. So I start diging service by service and I found the case.... 

Remeber If you frontend-developer start overwrite global input You should cut his hands...

This issue is closed. 

Thanks, best regards,
Zdanc32

**Comment by joeldenning** [comment]
I'm glad to hear that things are working now for you!

**Comment by kalchuka** [comment]
Hello How do i add vuetify as a Shared dependencies
 to a single-spa application

**Comment by joeldenning** [comment]
@kalchuka your question is unrelated to the original issue. Please ask it in a new github issue or in the [single-spa slack](https://single-spa.js.org/docs/getting-started-overview)
