### ISSUE TITLE
A proper way to use vue-router with Vue 3

### ISSUE THREAD

**Issue by iplus26** [single-spa/single-spa-vue#58]
I'm new to Vue, but I've been working with single-spa in our team these days and gave Vue 3 a try.

It seems that passing `router` to `appOptions` not working with new global API `createApp` (differs from the way it works with the `Vue` constructor in Vue 2).

```javascript
const vueLifecycles = singleSpaVue({
  createApp,
  appOptions: {
    render() {
      return h(App);
    },
    router, // NOT WORKING
  },
});
```

`single-spa-vue` docs only mentions the way to use Vue 3 `createApp` in [Vue 3 chapter](https://single-spa.js.org/docs/ecosystem-vue/#vue-3), and the way to use `vue-router` in [Custom props chapter](https://single-spa.js.org/docs/ecosystem-vue/#custom-props). It costs me a lot of time debugging why router is not working, and at last I figured it out the maybe correct way to combine Vue 3, `vue-router` and `single-spa-vue` together.

```javascript
// Correct way! 
const vueLifecycles = singleSpaVue({
    createApp: (...args) => {
        const vueInstance = createApp(...args);
        vueInstance.use(router);
        return vueInstance;
    },
    appOptions,
});
```

Since `single-spa-vue` doesn't expose vue instances to users, I have to "hijack" the createApp method to get the instance. BTW, this solution is also mentioned in [Vue migration docs](https://v3.vuejs.org/guide/migration/global-api.html#share-configurations-among-apps). 

I'm wondering if anything can be done in `single-spa-vue`? Maybe a new `router` option or generic `plugins` option can be added, or at least mention the usage above in docs? I'm happy to submit a pr if you can pick any of the ideas.

**Comment by iplus26** [comment]
Some thoughts:

### generic `plugins` option

```javascript
// usage
singleSpaVue({ plugins: [router] });

// single-spa-vue implementation
// before `vueInstance.mount(el)`
userOpt.plugins.forEach(plugin => vueInstance.use(plugin));
```


If you don't wanna change API of `single-spa-vue` for now, I'm also willing to help with single-spa docs!

**Comment by filoxo** [comment]
Yea this is a good observation. We do provide the instance as described at the end of this section here: https://single-spa.js.org/docs/ecosystem-vue/#usage but that happens after `.mount` has been called, so adding a router after this doesn't work as expected (at least from my quick test). Initially, I agree that an option could be exposed that provides a list of plugins to be used. Though I think I'd prefer to have it called `use` to match the Vue api. 

I wonder if instead we can provide the app instance in bootstrap and allow users to provide additional things there. The [Vue 3 instance API](https://v3.vuejs.org/guide/migration/global-api.html#a-new-global-api-createapp) is a lot more than just `.use` so hooking into bootstrap would be much more flexible is possible.

**Comment by joeldenning** [comment]
Thanks for the research on this @iplus26 and @filoxo. I agree we should update single-spa-vue to allow the user to modify the instance any way they'd like. As an alternative to the workaround you found, you can access the vue instance as the return value of the mount lifecycle:

```js
const vueLifecycles = singleSpaVue({
  createApp,
  appOptions: {
    render() {
      return h(App, {
        props: {
        },
      });
    },
  },
});

export const bootstrap = vueLifecycles.bootstrap;
export const mount = props => vueLifecycles.mount(props).then(vueInstance => {
  vueInstance.use(router)
})
export const unmount = vueLifecycles.unmount
```

See code below that shows why this works:

https://github.com/single-spa/single-spa-vue/blob/5162f780ddd70d6c88e4088e60ea58a0430761a9/src/single-spa-vue.js#L134

However, the above is perhaps a bit tedious and could be improved. I agree with @filoxo that it would be better just to let the user do anything they want to the Vue instance. Perhaps an api like this??

```js
singleSpaVue({
  createApp,
  appOptions: {...},
  handleInstance: vueInstance => {
    vueInstance.use(router)
    // do anything else to the instance, too
  }
})
```

**Comment by iplus26** [comment]
Thank you guys for your insights! 

However, I'd like to mention that I've tried this workaround to extend `mount` method, but it didn't work. `app.use(router)` must be executed **before** Vue instance mounted, as @filoxo mentioned, and after `createApp`. 

So do we all agree that we should provide a new api, which will be executed between `createApp` and `app.mount`? Would `getInstance` still be a good name? If so, I'd like to submit a PR serval hours later (It's late night here 😁)

**Comment by filoxo** [comment]
I was able to put together an example of the additional mount lifecycle function last night, and it does not work properly. You can see the code here here: https://github.com/filoxo/test-single-spa-vue3-router
I think its because createApp's mount is called before the  user-provided mount function is called so the app has already started before the router is provided; `.use` appears to need to be called before `.mount`. I could totally be wrong though, I'm not a daily Vue user.

**Comment by filoxo** [comment]
ha nice! Looks like we've come to the same conclusion.

**Comment by joeldenning** [comment]
> I'd like to mention that I've tried this workaround to extend mount method, but it didn't work. app.use(router) must be executed before Vue instance mounted, as @filoxo mentioned, and also after createApp(so we can get the instance).

Ah I see. Thanks for the clarification. Yes it sounds like we need the `handleInstance`. Thanks for your work in putting together #59
