### ISSUE TITLE
CLI creates Parcel app with Vue and Typescript throws errors on `yarn serve`

### ISSUE THREAD

**Issue by creynir** [single-spa/single-spa-vue#60]
I was trying to create parcel single-spa app via cli with Vue3 + TypeScript and when I'm trying to run I get errors:
![image](https://user-images.githubusercontent.com/33603036/95679802-e86bf800-0bdd-11eb-9d9d-23552069a64d.png)
![image](https://user-images.githubusercontent.com/33603036/95679833-089bb700-0bde-11eb-8b23-0fc995b76f85.png)

Since I'm pretty new to TS I have little to no idea how to fix it. Would appreciate any help here

**Comment by filoxo** [comment]
I'm transferring this to the single-spa-vue repo because this is a problem with the [included types](https://github.com/single-spa/single-spa-vue/blob/main/types/single-spa-vue.d.ts). We added `createApp` to the API to support Vue 3 but forgot about the types.

**Comment by filoxo** [comment]
@creynir I opened up a PR with a fix for this. Can you try copying over the types into the types file for single-spa-vue in your node_modules directory? I'd like to validate with another project in addition to my own.
