### ISSUE TITLE
Vue instance is not mounted at the exact element `el`

### ISSUE THREAD

**Issue by iplus26** [single-spa/single-spa-vue#64]
Hi, joel, it's been a month since I submitted a (my only) pr here 🤝 

So the story is, I maintain a "micro-frontend website" in our team and one of my client's trying to migrate his "ssr vue application" into our single-spa arch. 

After he reported the issue that the vue instance is not mounted at `#app`, I dig a little and found that: whether `appOptions.el` is provided, `single-spa-vue` append `" .single-spa-container"` selector after the original selector. In this case, the `el` selector finally passed to `new Vue` is `"#app .single-spa-container"`.

https://github.com/single-spa/single-spa-vue/blob/6ead44637eeb1b28c3bb76f2096fabaef899251d/src/single-spa-vue.js#L100

I suppose this line is brought in pr #34 to solve issue #33 .

I'm using `qiankun` with single-spa-* plugins. As you know, instead of JS entry, `qiankun` supports "html entry", therefore, ssr support may be a not only possible but may be important feature to us. Under this situation, I'm wondering there's any approach that we can leave `el` selector alone, and let Vue instance mount on the exact element? Maybe something like: 

```javascript
if (!opts.exactEl) {
 appOptions.el = appOptions.el + " .single-spa-container"; 
}
```

**Comment by iplus26** [comment]
I found `qiankun` choose not to use `single-spa-vue` in its [official examples](https://github.com/umijs/qiankun/blob/master/examples/vue/src/main.js#L51-L66). 👀 

Therefore, if it's a hard decision for you, joel, feel free to close the issue and I'm also willing to maintain a fork of single-spa-vue for our ssr users to use.

**Comment by joeldenning** [comment]
Hi @iplus26, this behavior is intentional. We did it so that the behavior of single-spa-vue is consistent with the behavior of all the other frameworks. For all of the frameworks that we support, we append to props.domElement instead of replacing it. The Vue library replaces the element that it is mounted to, so we wrapped it in a container so that we could simulate appending instead of replacing.

**Comment by iplus26** [comment]
I see. Thank you for your reply and insights. 

I'm closing this issue for now.

**Comment by raihle** [comment]
As far as I understand, this interferes with server-side rendering (or rather, client-side hydration) as Vue expects the client-side app to mount on the root element *rendered by the server-side Vue app*. I don't love it, but as an app developer you can work around this by simply adding a `single-spa-container` class to your root element, which will match the selector added by single-spa-vue.

**Comment by iplus26** [comment]
> As far as I understand, this interferes with server-side rendering (or rather, client-side hydration) as Vue expects the client-side app to mount on the root element rendered by the server-side Vue app. I don't love it, but as an app developer you can work around this by simply adding a `single-spa-container` class to your root element, which will match the selector added by single-spa-vue.

Yes, that's another approach. However, as you mentioned, it's a bit tricky so I decide to "betray" single-spa-vue and implement `mount` & `unmount` myself.

**Comment by joeldenning** [comment]
Thanks for the clarifications here about how this relates to SSR. I'm open to making this a configurable option. Would either of you care to create a pull request doing so? Maybe like this:

```js
const lifecycles = singleSpaVue({
  // all the normal options
  ...,
  // new option
  replaceMode: true
})
```

**Comment by iplus26** [comment]
@joeldenning Maybe I can spare some time this weekend.

**Comment by MarcoBomfim** [comment]
@joeldenning  is #73  enough? Or I'm being way to simplistic?

**Comment by MarcoBomfim** [comment]
@iplus26, @raihle, the change is merged, if you can try it out and let me know how it goes, that would be great!
