### ISSUE TITLE
Is there a way to make it work with Quasar framework?

### ISSUE THREAD

**Issue by lopes-gustavo** [single-spa/single-spa-vue#65]
Using quasar with starter kit, I'm not able to directly manipulate `vue.config.js` or `main.js`.

I can change the underlying `webpack.config` and update, for example, `libraryTarget` to `umd`.

But when I try to import it on the "container" (using `System.import`), my exported functions `bootstrap, mount and unmount` are not exported...

Does `single-spa-vue` intend to make quasar work as well?

**Comment by joeldenning** [comment]
Here is a link to [a discussion about quasar + single-spa](https://single-spa.slack.com/archives/CGGUQJMK6/p1603432684039100).

The reason that your mount/unmount functions aren't available is probably due to having multiple webpack entry points. The first webpack entry in the array is the one whose exports matter. Or of it's an object of key/value pairs, each entry point will have its own exports.

**Comment by joeldenning** [comment]
Quasar isn't something I've used before - I am happy to help guide you in using it, but you'll be one of the first doing so.

**Comment by lopes-gustavo** [comment]
I don't have access to this slack workspace.

But I figured it out how to make it work. It's a bit hackish, but it does the job.
I explained how I made it work [here, on Quasar github](https://github.com/quasarframework/quasar/issues/6601).

But mainly, I create another entrypoint and use `createApp` from `.quasar/app.js` to access the Vue instance.
It's hackish because `.quasar/app.js` is dynamically created and we're not supposed to use it.

I believe the issue about "using quasar with single-spa" is best suited for Quasar issues page, but it'd be a nice feature to use a single line import from `single-spa-vue` or maybe `single-spa-quasar` (like we can do in pure Vue applications)

**Comment by filoxo** [comment]
In case you're interested in the future, the link to join the single-spa Slack is in the footer of the documentation site https://single-spa.js.org/.

**Comment by lopes-gustavo** [comment]
For anyone interested, I created a repo with the minimum setup needed to make quasar work with single-spa.
I tried to let the default setup as pure as possible

https://github.com/lopes-gustavo/quasar-single-spa

**Comment by Karnith** [comment]
I created a repo with quasar v2 & single-spa

https://github.com/ourparentcenter/single-spa-quasar2-example
