### ISSUE TITLE
Vue 3 requires unsafe-eval in dev

### ISSUE THREAD

**Issue by filoxo** [single-spa/single-spa-vue#66]
Something about the Webpack config used for Vue 3 has introduced code that executes `'unsafe-eval'` in the browser, though only in development mode. I'm opening this issue for if/when someone has the time to delve into which plugin/loader/whatever in Webpack is the cause of this. For now this can be worked around by allowing `'unsafe-eval'` in the CSP if running locally. 
```ejs
<meta http-equiv="Content-Security-Policy" content="default-src 'self' https: localhost:*; script-src <% if (isLocal) { %>'unsafe-eval'<% }%> 'unsafe-inline' https: localhost:*; ... ">
```
Another option is to simply remove the CSP but having one is a best-practice to increase the site's security.

See for original comment https://github.com/lordsteggu/gz-root/pull/1#discussion_r526312864

**Comment by joeldenning** [comment]
Webpack's devtool option defaults to creating sourcemaps that require the use of eval. It's likely that this is why it's needed in Vue CLI for Vue 3.

I'm open to adding `unsafe-eval` to create-single-spa's root config. I still think it's better to have a CSP than to not, if only to educate people on what a CSP is.
