### ISSUE TITLE
Vue 3 support: Rename lifecycle method destroyed to unmounted

### ISSUE THREAD

**Issue by pjammula** [single-spa/single-spa-vue#78]
In vue3, lifecycle method destroyed is renamed to unmounted. Please handle this similar to support both vue 2 and vue 3.
Maybe similar to how render methos was handled.

Warning in console:
![image](https://user-images.githubusercontent.com/42665900/122563870-5c5e7a00-d062-11eb-814f-6e45cb1aa00a.png)

**Comment by joeldenning** [comment]
Thanks for the bug report, fix is at #79

**Comment by joeldenning** [comment]
Fixed at https://github.com/single-spa/single-spa-vue/releases/tag/v2.4.1
