### ISSUE TITLE
Standalone app testing

### ISSUE THREAD

**Issue by jkblume** [single-spa/single-spa-vue#80]
Hello, thank you very much for the work in this project. I have a question about standalone testing of a single-spa-vue app. I manage very well to include the app in my orechstrator setup. You can find a lot of documentation for this accordingly. However, I am wondering: how can I launch my app standalone without the orchestrator project to be able to develop on it. I use the standard build process and also like to search for literature or documentation to understand what I need to change in the project setup to launch a functional standalone app. Link to repo / directory of vue single spa project: https://github.com/jkblume/family-dashboard/tree/master/randomphoto/frontend

Thanks for your help.

**Comment by joeldenning** [comment]
See https://github.com/single-spa/standalone-single-spa-webpack-plugin.

For projects using vue-cli-plugin-single-spa, the `serve:standalone` script lets you do this: https://github.com/single-spa/vue-cli-plugin-single-spa/blob/e3746601a76346f6b12bc8b3e756b93ae656ae88/generator.js#L35
