### ISSUE TITLE
installing vuetify in  single-spa 

### ISSUE THREAD

**Issue by kalchuka** [single-spa/single-spa-vue#90]
Hello How do i add vuetify as a Shared dependencies
to a single-spa application

using vue add vuetify on the application gives me this error

Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.

**Comment by kalchuka** [comment]
so i am using vue2

**Comment by joeldenning** [comment]
Please do not post the same question in two places (you also posted this in a different issue).

To add any library as a shared dependency, follow the instructions at https://single-spa.js.org/docs/recommended-setup#sharing-with-import-maps. vuetify publishes a UMD build to npm that you can use in your systemjs import map: https://cdn.jsdelivr.net/npm/vuetify@2.6.0/dist/vuetify.js
