### ISSUE TITLE
Fail when upload s3 static website

### ISSUE THREAD

**Issue by ahelord** [single-spa/single-spa-vue#99]
Hello, I am trying to do tests with the latest version of vite and vue 3, locally it works for me with the vite server, but when I try to deploy the content of /dist to s3, it fail  in https://single-spa-playground.org/ , could you include a tutorial for this please

**Comment by filoxo** [comment]
Deployment is tangential but not directly related to single-spa. Closing, as we don't have the resources to create an example of this for you.
